def generate_report(data):
    html = f"""
    <html>
    <head>
        <title>QuickBiz Health Check</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                padding: 40px;
            }}
            h1 {{
                color: #2c3e50;
            }}
            .risk {{
                font-size: 18px;
                font-weight: bold;
                color: {'red' if data['risk'] == 'HIGH' else 'orange' if data['risk'] == 'MEDIUM' else 'green'};
            }}
        </style>
    </head>
    <body>
        <h1>QuickBiz Health Check™</h1>
        <p><i>Instant Financial Reality Check for Small Businesses</i></p>

        <hr>

        <p><b>Profit:</b> {data['profit']}</p>
        <p><b>Profit Margin:</b> {data['profit_margin']}%</p>
        <p><b>Monthly Burn Rate:</b> {data['burn_rate']}</p>
        <p><b>Cash Runway:</b> {data['runway']} months</p>

        <p class="risk">Risk Level: {data['risk']}</p>

        <p><b>Recommendation:</b><br>{data['advice']}</p>

        <hr>
        <p style="font-size:12px;">Generated by QuickBiz Health Check</p>
    </body>
    </html>
    """
    return html
