from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

def generate_report(data, filename="QuickBiz_Report.pdf"):
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(filename)

    content = [
        Paragraph("<b>QuickBiz Health Check Report</b>", styles["Title"]),
        Paragraph(f"Profit: {data['profit']}", styles["Normal"]),
        Paragraph(f"Profit Margin: {data['profit_margin']}%", styles["Normal"]),
        Paragraph(f"Monthly Burn Rate: {data['burn_rate']}", styles["Normal"]),
        Paragraph(f"Cash Runway (months): {data['runway']}", styles["Normal"]),
        Paragraph(f"Risk Level: <b>{data['risk']}</b>", styles["Normal"]),
        Paragraph(f"Recommendation: {data['advice']}", styles["Normal"]),
        Paragraph("<br/>Generated by QuickBiz Health Check", styles["Italic"])
    ]

    doc.build(content)
